pipeline {
    agent {
        docker {
            image 'node:18-alpine'  // or ubuntu, maven, nginx, etc.
        }
    }

    stages {
        stage('Run') {
            steps {
                echo 'Running from official Docker Hub image'
                sh 'node -v'
            }
        }
    }
}
