pipeline {
  agent {
    docker {
      image 'node:16-alpine'
    }
  }

  stages {
    stage('Docker Auth and Test') {
      steps {
        script {
          withDockerRegistry([credentialsId: 'docker-creds', url: 'https://hub.docker.com/']) {
            sh 'node --version'
          }
        }
      }
    }
  }
}
